-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-02 15:40:23 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
set echo on
SPOOL pat_schema_output.txt
-- Group id: G051
-- Students name: Sia Yi Bin, Leong Xin Ru, Muhammad Mustafa Khan 


DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE driver_training_completion CASCADE CONSTRAINTS;

DROP TABLE feature CASCADE CONSTRAINTS;

DROP TABLE features_addition CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE location CASCADE CONSTRAINTS;

DROP TABLE noc CASCADE CONSTRAINTS;

DROP TABLE official CASCADE CONSTRAINTS;

DROP TABLE training_module CASCADE CONSTRAINTS;

DROP TABLE trip CASCADE CONSTRAINTS;

DROP TABLE vehicle CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE driver (
    driver_id             NUMBER(4) NOT NULL,
    driver_given_name     VARCHAR2(50) NOT NULL,
    driver_family_name    VARCHAR2(50) NOT NULL,
    driver_license_number VARCHAR2(7) NOT NULL,
    driver_date_of_birth  DATE NOT NULL,
    driver_sec_cl_lvl     CHAR(1) NOT NULL,
    driver_is_suspended   CHAR(1) NOT NULL,
    vehicle_vin           VARCHAR2(17) NOT NULL
);

ALTER TABLE driver
    ADD CONSTRAINT chk_driver_sec_cl_lvl CHECK ( driver_sec_cl_lvl IN ( 'F', 'R' ) );

COMMENT ON COLUMN driver.driver_id IS
    'driver_id';

COMMENT ON COLUMN driver.driver_given_name IS
    'driver_given_name';

COMMENT ON COLUMN driver.driver_family_name IS
    'driver_family_name';

COMMENT ON COLUMN driver.driver_license_number IS
    'driver_license_number';

COMMENT ON COLUMN driver.driver_date_of_birth IS
    'driver_date_of_birth';

COMMENT ON COLUMN driver.driver_sec_cl_lvl IS
    'driver_security_clearance_level,  F - Full,  R - Restricted';

COMMENT ON COLUMN driver.driver_is_suspended IS
    'driver_is_suspended';

COMMENT ON COLUMN driver.vehicle_vin IS
    'vehicle_vin';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_id );

CREATE TABLE driver_training_completion (
    driver_id           NUMBER(4) NOT NULL,
    dtc_completion_date DATE NOT NULL,
    tm_code             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN driver_training_completion.driver_id IS
    'driver_id';

COMMENT ON COLUMN driver_training_completion.dtc_completion_date IS
    'dtc_completion_date';

COMMENT ON COLUMN driver_training_completion.tm_code IS
    'tm_code';

ALTER TABLE driver_training_completion ADD CONSTRAINT driver_training_completion_pk PRIMARY KEY ( driver_id,
                                                                                                  tm_code );

CREATE TABLE feature (
    feature_boot_space         VARCHAR2(50) NOT NULL,
    feature_plating            VARCHAR2(50) NOT NULL,
    feature_blackout           VARCHAR2(50) NOT NULL,
    feature_mobile_wifi        CHAR(1) NOT NULL,
    feature_electric_tail_lift CHAR(1) NOT NULL,
    feature_carry              VARCHAR2(50) NOT NULL,
    feature_gps                CHAR(1) NOT NULL,
    vehicle_vin                VARCHAR2(17) NOT NULL,
    features_id                NUMBER(8) NOT NULL
);

COMMENT ON COLUMN feature.feature_boot_space IS
    'feature_boot_space';

COMMENT ON COLUMN feature.feature_plating IS
    'feature_plating';

COMMENT ON COLUMN feature.feature_blackout IS
    'feature_blackout';

COMMENT ON COLUMN feature.feature_mobile_wifi IS
    'feature_mobile_wifi';

COMMENT ON COLUMN feature.feature_electric_tail_lift IS
    'feature_electric_tail_lift';

COMMENT ON COLUMN feature.feature_carry IS
    'feature_carry';

COMMENT ON COLUMN feature.feature_gps IS
    'feature_GPS';

COMMENT ON COLUMN feature.vehicle_vin IS
    'vehicle_vin';

COMMENT ON COLUMN feature.features_id IS
    'features_id';

ALTER TABLE feature ADD CONSTRAINT feature_pk PRIMARY KEY ( vehicle_vin );

CREATE TABLE features_addition (
    features_id   NUMBER(8) NOT NULL,
    features_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN features_addition.features_id IS
    'features_id';

COMMENT ON COLUMN features_addition.features_name IS
    'features_name';

ALTER TABLE features_addition ADD CONSTRAINT features_addition_pk PRIMARY KEY ( features_id );

CREATE TABLE language (
    language_iso639_1code VARCHAR2(8) NOT NULL,
    language_name         CHAR(2) NOT NULL,
    driver_id             NUMBER(4) NOT NULL
);

COMMENT ON COLUMN language.language_iso639_1code IS
    'language_iso639_1code';

COMMENT ON COLUMN language.language_name IS
    'language_name';

COMMENT ON COLUMN language.driver_id IS
    'driver_id';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( language_iso639_1code,
                                                              driver_id );

CREATE TABLE location (
    location_id      NUMBER(2) NOT NULL,
    location_name    VARCHAR2(50) NOT NULL,
    location_type    VARCHAR2(50) NOT NULL,
    location_address VARCHAR2(50) NOT NULL,
    trip_id          NUMBER(4) NOT NULL
);

COMMENT ON COLUMN location.location_id IS
    'location id';

COMMENT ON COLUMN location.location_name IS
    'location name';

COMMENT ON COLUMN location.location_type IS
    'location type';

COMMENT ON COLUMN location.location_address IS
    'location address';

COMMENT ON COLUMN location.trip_id IS
    'trip_id';

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( location_id );

CREATE TABLE noc (
    noc_ioc_code            VARCHAR2(50) NOT NULL,
    noc_country_region_name VARCHAR2(50) NOT NULL,
    noc_population          VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN noc.noc_ioc_code IS
    'noc_ioc_code';

COMMENT ON COLUMN noc.noc_country_region_name IS
    'noc_country_region_name';

COMMENT ON COLUMN noc.noc_population IS
    'noc_population';

ALTER TABLE noc ADD CONSTRAINT noc_pk PRIMARY KEY ( noc_ioc_code );

CREATE TABLE official (
    official_olymic_id VARCHAR2(7) NOT NULL,
    official_name      VARCHAR2(50) NOT NULL,
    official_role      VARCHAR2(50) NOT NULL,
    noc_ioc_code       VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN official.official_olymic_id IS
    'official_olymic_id';

COMMENT ON COLUMN official.official_name IS
    'official_name';

COMMENT ON COLUMN official.official_role IS
    'official_role';

COMMENT ON COLUMN official.noc_ioc_code IS
    'noc_ioc_code';

ALTER TABLE official ADD CONSTRAINT official_pk PRIMARY KEY ( official_olymic_id );

CREATE TABLE training_module (
    tm_code          NUMBER(7) NOT NULL,
    tm_name          VARCHAR2(50) NOT NULL,
    tm_description   VARCHAR2(50) NOT NULL,
    tm_duration      NUMBER(2) NOT NULL,
    tm_expiry_period DATE NOT NULL
);

COMMENT ON COLUMN training_module.tm_code IS
    'tm_code';

COMMENT ON COLUMN training_module.tm_name IS
    'tm_name';

COMMENT ON COLUMN training_module.tm_description IS
    'tm_description';

COMMENT ON COLUMN training_module.tm_duration IS
    'tm_duration';

COMMENT ON COLUMN training_module.tm_expiry_period IS
    'tm_expiry_period ';

ALTER TABLE training_module ADD CONSTRAINT training_module_pk PRIMARY KEY ( tm_code );

CREATE TABLE trip (
    vehicle_vin                    VARCHAR2(17) NOT NULL,
    trip_number_of_passengers      NUMBER(2) NOT NULL,
    trip_int_pick_up_date_time     DATE NOT NULL,
    trip_int_drop_off_date_time    DATE NOT NULL,
    trip_id                        NUMBER(4) NOT NULL,
    trip_actual_pick_up_date_time  DATE NOT NULL,
    trip_actual_drop_off_date_time DATE NOT NULL,
    official_olymic_id             VARCHAR2(7) NOT NULL,
    driver_id                      NUMBER(4) NOT NULL
);

COMMENT ON COLUMN trip.vehicle_vin IS
    'vehicle_vin';

COMMENT ON COLUMN trip.trip_number_of_passengers IS
    'trip_number_of_passengers';

COMMENT ON COLUMN trip.trip_int_pick_up_date_time IS
    'trip_intended_pick_up_date_time';

COMMENT ON COLUMN trip.trip_int_drop_off_date_time IS
    'trip_intended_drop_off_date_time';

COMMENT ON COLUMN trip.trip_id IS
    'trip_id';

COMMENT ON COLUMN trip.trip_actual_pick_up_date_time IS
    'trip_actual_pick_up_date_time';

COMMENT ON COLUMN trip.trip_actual_drop_off_date_time IS
    'trip_actual_drop_off_date_time';

COMMENT ON COLUMN trip.official_olymic_id IS
    'official_olymic_id';

COMMENT ON COLUMN trip.driver_id IS
    'driver_id';

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( trip_id );

ALTER TABLE trip
    ADD CONSTRAINT trip_nk UNIQUE ( vehicle_vin,
                                    official_olymic_id,
                                    driver_id );

CREATE TABLE vehicle (
    vehicle_vin              VARCHAR2(17) NOT NULL,
    vehicle_registeration_no VARCHAR2(8) NOT NULL,
    vehicle_make             VARCHAR2(50) NOT NULL,
    vehicle_curr_odometer    NUMBER(6) NOT NULL,
    vehicle_seats            NUMBER(2) NOT NULL,
    vehicle_model            VARCHAR2(50) NOT NULL,
    vehicle_year             DATE NOT NULL,
    vehicle_features         VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN vehicle.vehicle_vin IS
    'vehicle_vin';

COMMENT ON COLUMN vehicle.vehicle_registeration_no IS
    'vehicle_registeration_no';

COMMENT ON COLUMN vehicle.vehicle_make IS
    'vehicle_make';

COMMENT ON COLUMN vehicle.vehicle_curr_odometer IS
    'vehicle_curr_odometer';

COMMENT ON COLUMN vehicle.vehicle_seats IS
    'vehicle_seats';

COMMENT ON COLUMN vehicle.vehicle_model IS
    'vehicle_model';

COMMENT ON COLUMN vehicle.vehicle_year IS
    'vehicle_year';

COMMENT ON COLUMN vehicle.vehicle_features IS
    'vehicle_features';

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( vehicle_vin );

ALTER TABLE driver_training_completion
    ADD CONSTRAINT driver_dtc FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE language
    ADD CONSTRAINT driver_language FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE trip
    ADD CONSTRAINT driver_trip FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE feature
    ADD CONSTRAINT features_addition FOREIGN KEY ( features_id )
        REFERENCES features_addition ( features_id );

ALTER TABLE official
    ADD CONSTRAINT noc_official FOREIGN KEY ( noc_ioc_code )
        REFERENCES noc ( noc_ioc_code );

ALTER TABLE trip
    ADD CONSTRAINT official_trip FOREIGN KEY ( official_olymic_id )
        REFERENCES official ( official_olymic_id );

ALTER TABLE driver_training_completion
    ADD CONSTRAINT tm_dtc FOREIGN KEY ( tm_code )
        REFERENCES training_module ( tm_code );

ALTER TABLE location
    ADD CONSTRAINT trip_location FOREIGN KEY ( trip_id )
        REFERENCES trip ( trip_id );

ALTER TABLE feature
    ADD CONSTRAINT vehicle_features FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );

ALTER TABLE trip
    ADD CONSTRAINT vehicle_trip FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SPOOL off
set echo off